### ISSUE TITLE
Get battery status? + suggestion

### ISSUE THREAD

**Issue by alexisml** [cadavre/miio_gateway#19]
1) First of all a question: is there any way to get the battery status of a device?

2) Suggestion: I had a hard time figuring out how to set up a termometer/hygrometer/thing. I would suggest adding an example, specifying that you need to set up the 3 sensors individually (repeat the same sid with 3 different classes).

**Comment by aburghelea** [comment]
Hey there. 

For the first part it greatly depends on the data that the gateway is reporting. If there is the battery status over there , in theory you could. I have some both Xiaomi and Aquaria to play with in the next couple of weeks and will get back to you, if I see something.

For the second part, after you join the device via the [join_zigbee]( https://github.com/cadavre/miio_gateway#adding-sensor-to-ha) service and get the SID you just add something like. 

```
sensors:
  - sid: lumi.158d0003d2d1dd
    friendly_name: Bedroom Temperature
    class: temperature
    restore: true
  - sid: lumi.158d0003d2d1dd
    friendly_name: Bedroom Humidity
    class: humidity
    restore: true
```
